SELECT N.IDENTIFIER,
  'GB' AS REGISTRY_CODE,
  TO_CHAR(NH.CREATED_DATE,'YYYY') AS YEAR,
  N.TYPE,
  SUM(NH.TARGET_VALUE) AS AMOUNT,
  UB.UNIT_TYPE,
  SUM(UB.END_BLOCK - UB.START_BLOCK + 1) AS UB_AMOUNT
FROM ITL_NOTIFICATION N
LEFT OUTER JOIN ITL_NOTIFICATION_HISTORY NH ON N.ID = NH.NOTICE_LOG_ID
LEFT OUTER JOIN ITL_NOTIFICATION_BLOCK RNB ON N.ID = RNB.NOTICE_LOG_ID
LEFT OUTER JOIN unit_block ub
ON ub.start_block                                    >= rnb.unit_serial_block_start
AND ub.end_block                                     <= rnb.unit_serial_block_end
AND UB.ORIGINATING_COUNTRY_CODE                       = RNB.ORIGINATING_REGISTRY_CODE
WHERE nh.created_date < ?
  AND n.type IN ('IMPENDING_EXPIRY_OF_TCER_AND_LCER','REVERSAL_OF_STORAGE_FOR_CDM_PROJECT','NON_SUBMISSION_OF_CERTIFICATION_REPORT_FOR_CDM_PROJECT','NET_REVERSAL_OF_STORAGE_OF_A_CDM_CCS_PROJECT','NON_SUBMISSION_OF_VERIFICATION_REPORT_FOR_A_CDM_CCS_PROJECT')
GROUP BY N.ID,N.IDENTIFIER,
  NH.CREATED_DATE,
  N.TYPE,
  UB.UNIT_TYPE
HAVING NH.CREATED_DATE = (SELECT MAX(CE.CREATED_DATE) FROM ITL_NOTIFICATION_HISTORY CE WHERE N.ID = CE.NOTICE_LOG_ID)