export enum TrustedAccountListApiRequestType {
  SAME_ACCOUNT_HOLDER = 'SAME_ACCOUNT_HOLDER',
  OTHER_ALL = 'OTHER_ALL',
  OTHER_PENDING_APPROVAL = 'OTHER_PENDING_APPROVAL',
  OTHER_APPROVED_OR_ACTIVATED = 'OTHER_APPROVED_OR_ACTIVATED',
  ELIGIBLE_FOR_REMOVAL = 'ELIGIBLE_FOR_REMOVAL'
}
