package gov.uk.ets.reports.model.messaging;

import gov.uk.ets.reports.model.ReportStatus;
import gov.uk.ets.reports.model.RequestingSystem;
import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Event generated by report-generator when the report has finished generating
 * (on success or error).
 */
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@ToString
@EqualsAndHashCode(of = {"id"})
@Builder
public class ReportGenerationEvent implements Serializable {

    private static final long serialVersionUID = 1L;
    private Long id;
    private ReportStatus status;
    private String fileLocation;
    private RequestingSystem requestingSystem;
    private LocalDateTime generationDate;
    private Long fileSize;
}
