package gov.uk.ets.registry.api.migration.domain;

public enum MigratorName {

    TRANSACTION_SIGNING_MIGRATOR,

    USER_ROLES_MIGRATOR,

    USER_KNOWN_AS_ATTRIBUTE_MIGRATOR,

    ALLOCATION_CLASSIFICATION_MIGRATOR,
    
    ALLOCATION_WITHHOLD_STATUS_MIGRATOR,

    USER_EMAIL_MIGRATOR,

    REJECTED_ACCOUNTS_MIGRATOR,

    ACCOUNTS_COMPLIANCE_MIGRATOR,

    RUNNING_BALANCE_MIGRATOR,
    
    ACCOUNT_OPENING_INST_TRANSFER_MIGRATOR,
    
    COUNTRY_ATTRIBUTES_MIGRATOR,

    KYOTO_GOV_ACCOUNT_OPENING_MIGRATOR,

    ACCOUNT_OPENING_TASK_MIGRATOR,

    TRUSTED_ACCOUNT_STATUS,

    COMPLIANT_ENTITY_REGULATOR_MIGRATOR,

    TASK_SEARCH_METADATA_MIGRATOR,

    ACCOUNT_TRANSFER_TASK_MIGRATOR,

    PARENT_TASK_DEADLINE_MIGRATOR,

    WORK_MOBILE_PHONE_ATTRIBUTE_MIGRATOR,

    PUBLIC_ACCOUNT_IDENTIFIER_MIGRATOR,

    STATIC_COMPLIANCE_STATUS_MIGRATOR,

    CLAIM_ACCOUNT_CODE_MIGRATOR

}
