export enum RequestDocumentsOrigin {
  ACCOUNT_OPENING_TASK,
  ACCOUNT_DETAILS,
  USER,
  AUTHORIZED_REPRESENTATIVE_ADDITION_TASK,
  AUTHORIZED_REPRESENTATIVE_REPLACEMENT_REQUEST,
  ACCOUNT_HOLDER_UPDATE_DETAILS_TASK,
  ACCOUNT_TRANSFER_TASK,
  CHANGE_ACCOUNT_HOLDER_TASK,
}
