@QueryEntities({
    AuthenticationExecutionEntity.class,
    AuthenticationFlowEntity.class,
    AuthenticatorConfigEntity.class,
    ClientAttributeEntity.class,
    ClientEntity.class,
    ClientInitialAccessEntity.class,
    ClientScopeAttributeEntity.class,
    ClientScopeClientMappingEntity.class,
    ClientScopeEntity.class,
    ClientScopeRoleMappingEntity.class,
    ComponentConfigEntity.class,
    ComponentEntity.class,
    CredentialEntity.class,
    DefaultClientScopeRealmMappingEntity.class,
    FederatedIdentityEntity.class,
    GroupAttributeEntity.class,
    GroupEntity.class,
    GroupRoleMappingEntity.class,
    IdentityProviderEntity.class,
    IdentityProviderMapperEntity.class,
    MigrationModelEntity.class,
    ProtocolMapperEntity.class,
    RealmLocalizationTextsEntity.class,
    RealmAttributeEntity.class,
    RealmAttributes.class,
    RealmEntity.class,
    RequiredActionProviderEntity.class,
    RequiredCredentialEntity.class,
    RoleAttributeEntity.class,
    RoleEntity.class,
    UserAttributeEntity.class,
    UserConsentClientScopeEntity.class,
    UserConsentEntity.class,
    UserEntity.class,
    UserFederationMapperEntity.class,
    UserFederationProviderEntity.class,
    UserGroupMembershipEntity.class,
    UserRequiredActionEntity.class,
    UserRoleMappingEntity.class,

})
package gov.uk.ets.keycloak.users.service.infrastructure;

import com.querydsl.core.annotations.QueryEntities;
import org.keycloak.models.jpa.entities.*;