FROM nginx:1.24
ENV XAUTH $HOME/.Xauthority

##RUN export 'http_proxy=http://153.89.205.10:8080' ;apt-get update
RUN apt-get update
RUN apt-get install -y apache2-utils
RUN rm /etc/nginx/conf.d/default.conf
RUN rm /etc/nginx/nginx.conf
COPY confs/nginx.conf /etc/nginx/nginx.conf
COPY confs/htpasswd.users /etc/nginx/htpasswd.users
COPY confs/page.conf /etc/nginx/conf.d/page.conf

COPY uk-ets-maintenance-page-web /usr/share/nginx/maintenance
COPY uk-ets-maintenance-page-web/resources /usr/share/nginx/resources
COPY uk-ets-maintenance-page-web/resources /usr/share/nginx/assets
COPY uk-ets-maintenance-page-web/resources/img /usr/share/nginx/assets/fonts
COPY uk-ets-maintenance-page-web/resources/img /usr/share/nginx/assets/images
COPY uk-ets-maintenance-page-web/resources/css /usr/share/nginx/maintenance/css
COPY uk-ets-maintenance-page-web/resources/img /usr/share/nginx/maintenance/img
#COPY uk-ets-maintenance-page-web/resources/js /usr/share/nginx/maintenance/js
