//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.07.23 at 01:00:45 PM EEST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:KyotoProtocol:RegistrySystem:SEF:2.0:0.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gov.uk.ets.reports.generator.kyotoprotocol.sef._2_0._0;